local opts = { noremap = true, silent = true }
local keymap = vim.api.nvim_set_keymap

keymap("n", "<Space>", "<Nop>", opts)
keymap("n", "<Space>q", ":q!<CR>", opts)
keymap("n", "<Space>nn", ":NERDTreeToggle<CR>", opts)
keymap("n", "<Space>nf", ":NERDTreeFocus<CR>", opts)
keymap("n", "<Space>ff", ":Telescope find_files<CR>", opts)
keymap("n", "<Space>fg", ":Telescope live_grep<CR>", opts)
keymap("n", "<Space>fb", ":Telescope buffers<CR>", opts)
keymap("n", "<Space>h", "<C-w>h", opts)
keymap("n", "<Space>j", "<C-w>j", opts)
keymap("n", "<Space>k", "<C-w>k", opts)
keymap("n", "<Space>l", "<C-w>l", opts)
keymap("n", "<S-Up>", ":resize -2<CR>", opts)
keymap("n", "<S-Down>", ":resize +2<CR>", opts)
keymap("n", "<S-Left>", ":vertical resize -2<CR>", opts)
keymap("n", "<S-Right>", ":vertical resize +2<CR>", opts)
keymap("n", "<S-l>", ":bnext <CR>", opts)
keymap("n", "<S-r>", ":bprevious <CR>", opts)
keymap("i", "jk", "<ESC>", opts)
keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
keymap('n', '<Space>ca', "<Cmd>lua vim.lsp.buf.code_action()<CR>", opts)
